# -*- coding: utf-8 -*-
"""
/***************************************************************************
 webservicetest
                                 A QGIS plugin
 test for a web service
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-01
        copyright            : (C) 2021 by origami
        email                : origami.desarrollo@origami.ec
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load webservicetest class from file webservicetest.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .WebServiceTest import webservicetest
    return webservicetest(iface)
